WORKERS: 8
PRINT_FREQ: 100
SAVE_FREQ: 2
PIN_MEMORY: False
OUTPUT_DIR: 'output'

CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

MODEL:
  IMAGE_SIZE:
    OW: 280 # origial width: 280
    H: 32
    W: 100   # resized width: 160
  NUM_CLASSES: 77
  NUM_HIDDEN: 256

DATASET:
  ROOT: ""
  ALPHABETS: "京沪津渝冀晋蒙辽吉黑苏浙皖闽赣鲁豫鄂湘粤桂琼川贵云藏陕甘青宁新学警港澳挂使领民航危0123456789ABCDEFGHJKLMNPQRSTUVWXYZ险品"
  PLATE_CHR: "#京沪津渝冀晋蒙辽吉黑苏浙皖闽赣鲁豫鄂湘粤桂琼川贵云藏陕甘青宁新学警港澳挂使领民航危0123456789ABCDEFGHJKLMNPQRSTUVWXYZ险品"
  HEIGHT: 48
  WIDTH: 168
  CHAR_FILE: 'config/plate.txt'
  SCALE_FACTOR: 0.25
  ROT_FACTOR: 30
  STD: 0.193
  MEAN: 0.588

TRAIN:
  BATCH_SIZE_PER_GPU: 200
  SHUFFLE: True
  LR: 0.001
  WD: 0.0
  LR_STEP: [60, 80]
  LR_FACTOR: 0.1
  MOMENTUM: 0.0
  NESTEROV: False
  RMSPROP_ALPHA:
  RMSPROP_CENTERED:

TEST:
  BATCH_SIZE_PER_GPU: 128
  SHUFFLE: True
  NUM_TEST: 1000
  NUM_TEST_DISP: 10
  